#!/usr/bin/env python3
"""Phase 4b of RCO_PLAN_NEW.md: build chat corpus v2, with on-policy replies.

Every sequence is a conversation rendered with the model's own chat
template; only the final assistant turn is scored.  The contexts come from
licensed sources (see ``SOURCES``) and from calibration v2's documents; the
scored replies are generated by the reference model itself (a Q6_K GGUF
quantized from the pinned BF16 checkpoint) with the model card's sampling.

Subcommands:

``prompts``
    Deterministic selection of the contexts: strata, languages, thinking
    on/off and the ``calibration``/``heldout`` split.  No source item of chat
    corpus v1 is reused.  Writes ``prompts.jsonl``.
``generate``
    Starts ``llama-server --jinja`` on the reference GGUF.  Per prompt:
    ``/apply-template`` renders the generation prompt, ``/tokenize`` (special
    tokens parsed) gives its tokens, and ``/completion`` samples the reply
    from exactly those tokens, returning the generated token ids (the
    end-of-generation token included).  Resumable; appends to
    ``generations.jsonl``.
``finalize``
    Tokens are prompt plus generated tokens; the scored targets are the
    generated ones.  Writes ``corpus.jsonl``, ``tokens.json`` and the
    manifest, in the format ``audit_qwen36_chat_kl.py`` reads.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import json
import os
import random
import signal
import subprocess
import sys
import time
import urllib.request
from pathlib import Path
from typing import Any

RCO = Path(__file__).resolve().parents[1]
ROOT = RCO.parents[1]
sys.path.insert(0, str(RCO / "tools"))
sys.path.insert(0, str(RCO / "src"))

from audit_qwen36_chat_generation import _post, _wait_ready  # noqa: E402
from audit_qwen36_q3k_viability import _atomic_json, _load_json, _sha256_file  # noqa: E402
from build_qwen36_chat_corpus import (  # noqa: E402
    MARKUP,
    SOURCES,
    _clean,
    _source_path,
    glaive_candidates,
    oasst2_candidates,
    openthoughts_candidates,
)
from release_corpus import canonical_json_bytes, sha256_bytes  # noqa: E402

SCHEMA = "rco.qwen36.chat_corpus_v2"
SEED = 20261010
SPLITS = ("calibration", "heldout")
MAX_CONTEXT_TOKENS = 2048
MAX_REASONING_THOUGHT_TOKENS = 2000
MAX_NEW_TOKENS = 6144
# Per split; each bucket draws twice this many and alternates the splits.
QUOTAS = {
    ("chat", "en"): 24, ("chat", "de"): 8, ("chat", "es"): 8, ("chat", "fr"): 8,
    ("chat", "it"): 8, ("chat", "pt"): 8,
    ("tool-call", "en"): 24, ("tool-answer", "en"): 24,
    ("reasoning", "en"): 48,
    ("document", "language"): 12, ("document", "knowledge"): 12,
    ("document", "reasoning"): 12, ("document", "code"): 12,
    ("document", "de"): 3, ("document", "es"): 3, ("document", "fr"): 3,
    ("document", "it"): 3, ("document", "pt"): 3,
}
SAMPLING = {
    True: {"temperature": 1.0, "top_p": 0.95, "top_k": 20, "min_p": 0.0,
           "presence_penalty": 1.5, "repeat_penalty": 1.0, "repeat_last_n": 64},
    False: {"temperature": 0.7, "top_p": 0.80, "top_k": 20, "min_p": 0.0,
            "presence_penalty": 1.5, "repeat_penalty": 1.0, "repeat_last_n": 64},
}
INSTRUCTIONS = {
    "language": ["Summarize what happens in this excerpt in a few sentences.",
                 "Who are the characters in this excerpt, and what do we learn about them?",
                 "Describe the tone and style of this passage, with examples from it."],
    "knowledge": ["Summarize the key facts in this text as a bulleted list.",
                  "Write three questions that this text answers, each with its answer.",
                  "Explain the main topic of this text to a high-school student."],
    "reasoning": ["Explain the argument made in this passage.",
                  "What is the main claim of this passage, and how is it supported?",
                  "Summarize this passage and point out the weakest step in its reasoning."],
    "code": ["Explain what this code does.",
             "Review this code and point out possible bugs or risks.",
             "Summarize the purpose of each function in this code."],
    "de": ["Fasse diesen Text in wenigen Sätzen zusammen.",
           "Worum geht es in diesem Text? Erkläre es einfach.",
           "Nenne die wichtigsten Aussagen dieses Textes als Liste."],
    "es": ["Resume este texto en unas pocas frases.",
           "¿De qué trata este texto? Explícalo de forma sencilla.",
           "Enumera las ideas principales de este texto."],
    "fr": ["Résume ce texte en quelques phrases.",
           "De quoi parle ce texte ? Explique-le simplement.",
           "Énumère les idées principales de ce texte."],
    "it": ["Riassumi questo testo in poche frasi.",
           "Di cosa parla questo testo? Spiegalo in modo semplice.",
           "Elenca le idee principali di questo testo."],
    "pt": ["Resuma este texto em poucas frases.",
           "Sobre o que é este texto? Explique de forma simples.",
           "Liste as ideias principais deste texto."],
}
V1_STRATUM_SOURCE = {"chat": "chat", "tool": "tool", "reasoning": "reasoning"}


def _tokenizer(model_dir: Path):
    from transformers import AutoTokenizer

    return AutoTokenizer.from_pretrained(model_dir, local_files_only=True)


def _context_tokens(tokenizer, messages, tools, thinking: bool) -> int:
    text = tokenizer.apply_chat_template(messages, tools=tools, tokenize=False,
                                         add_generation_prompt=True,
                                         enable_thinking=thinking)
    return len(tokenizer(text, add_special_tokens=False)["input_ids"])


def _v1_keys(v1_corpus: Path) -> dict[str, set[str]]:
    used: dict[str, set[str]] = {key: set() for key in SOURCES}
    with v1_corpus.open(encoding="utf-8") as handle:
        for line in handle:
            record = json.loads(line)
            used[record["stratum"]].add(str(record["source"]["key"]))
    return used


def _chat_contexts(path: Path, used: set[str]):
    for key, language, messages, _ in oasst2_candidates(path):
        if key in used:
            continue
        while messages and messages[-1]["role"] != "user":
            messages.pop()
        if messages:
            yield key, language.split("-")[0], messages, None, None


def _tool_contexts(path: Path, used: set[str]):
    """Yield (key, call context, answer context or None, tools)."""
    for key, _, messages, tools in glaive_candidates(path):
        if key in used:
            continue
        index = next((i for i, m in enumerate(messages) if m.get("tool_calls")), None)
        if index is None or index == 0 or messages[index - 1]["role"] != "user":
            continue
        answer = (index + 2 < len(messages) and messages[index + 1]["role"] == "tool"
                  and messages[index + 2]["role"] == "assistant"
                  and not messages[index + 2].get("tool_calls"))
        yield key, messages[:index], messages[:index + 2] if answer else None, tools


def _reasoning_contexts(path: Path, used: set[str], tokenizer):
    for key, _, messages, _ in openthoughts_candidates(path):
        if key in used:
            continue
        thought = messages[1]["reasoning_content"]
        if len(thought) > 8 * MAX_REASONING_THOUGHT_TOKENS:
            continue  # cheap pre-filter before tokenizing
        if len(tokenizer(thought, add_special_tokens=False)["input_ids"]) \
                > MAX_REASONING_THOUGHT_TOKENS:
            continue
        yield key, "en", [messages[0]], None, None


def _document_contexts(corpus: Path):
    with corpus.open(encoding="utf-8") as handle:
        for line in handle:
            document = json.loads(line)
            bucket = (document["language"] if document["stratum"] == "multilingual"
                      else document["stratum"])
            if not _clean(document["text"]):
                continue
            yield document["id"], bucket, document["text"]


def run_prompts(args) -> None:
    tokenizer = _tokenizer(args.model_dir)
    sources = args.sources
    used = _v1_keys(args.v1_corpus)
    records: list[dict[str, Any]] = []

    def take(stratum: str, candidates, build) -> set[str]:
        needed = {lang: 2 * q for (s, lang), q in QUOTAS.items() if s == stratum}
        taken = {lang: 0 for lang in needed}
        candidates = sorted(candidates, key=lambda item: str(item[0]))
        random.Random(f"{SEED}-v2-{stratum}").shuffle(candidates)
        for candidate in candidates:
            if all(taken[lang] >= needed[lang] for lang in needed):
                break
            bucket = candidate[1]
            if taken.get(bucket, 0) >= needed.get(bucket, 0):
                continue
            # Thinking alternates within each bucket; in the reasoning
            # stratum it is always on.
            thinking = stratum == "reasoning" or (taken[bucket] // 2) % 2 == 0
            built = build(candidate, taken[bucket])
            if built is None:
                continue
            messages, tools, source = built
            if _context_tokens(tokenizer, messages, tools, thinking) > MAX_CONTEXT_TOKENS:
                continue
            records.append({"stratum": stratum, "language": bucket,
                            "split": SPLITS[taken[bucket] % 2], "thinking": thinking,
                            "messages": messages, "tools": tools, "source": source})
            taken[bucket] += 1
        if any(taken[lang] < needed[lang] for lang in needed):
            raise RuntimeError(f"{stratum}: not enough candidates {taken} for {needed}")
        print(f"{stratum}: {taken} from {len(candidates)} candidates", flush=True)
        return {str(r["source"]["key"]) for r in records if r["stratum"] == stratum}

    chat_source = {**SOURCES["chat"]}
    take("chat", list(_chat_contexts(_source_path(sources, "chat"), used["chat"])),
         lambda c, _: (c[2], None, {**chat_source, "key": c[0]}))

    tool_source = {**SOURCES["tool"]}
    tool_items = list(_tool_contexts(_source_path(sources, "tool"), used["tool"]))
    # One pool: the answer stratum takes conversations with a function
    # response first; the call stratum takes from the rest.
    answered = take("tool-answer", [(k, "en", answer, tools)
                                    for k, _, answer, tools in tool_items if answer],
                    lambda c, _: (c[2], c[3], {**tool_source, "key": c[0]}))
    take("tool-call", [(k, "en", call, tools) for k, call, _, tools in tool_items
                       if k not in answered],
         lambda c, _: (c[2], c[3], {**tool_source, "key": c[0]}))

    reasoning_source = {**SOURCES["reasoning"],
                        "filter": f"R1 thought at most {MAX_REASONING_THOUGHT_TOKENS} tokens"}
    take("reasoning", list(_reasoning_contexts(_source_path(sources, "reasoning"),
                                               used["reasoning"], tokenizer)),
         lambda c, _: (c[2], None, {**reasoning_source, "key": c[0]}))

    def document(candidate, index):
        key, bucket, text = candidate
        instruction = random.Random(f"{SEED}-v2-instruction-{key}").choice(
            INSTRUCTIONS[bucket])
        body = f"```cpp\n{text}\n```" if bucket == "code" else text
        content = f"{instruction}\n\n{body}"
        if MARKUP.search(content):
            return None
        return ([{"role": "user", "content": content}], None,
                {"dataset": "calibration corpus v2", "key": key, "instruction": instruction,
                 "corpus_sha256": _sha256_file(args.documents)})

    take("document", list(_document_contexts(args.documents)), document)

    records.sort(key=lambda r: (SPLITS.index(r["split"]), r["stratum"], r["language"]))
    counters: dict[tuple[str, str], int] = {}
    for index, record in enumerate(records):
        bucket = (record["split"], record["stratum"])
        counters[bucket] = counters.get(bucket, 0) + 1
        record["id"] = f"chat-v2-{record['split']}-{record['stratum']}-{counters[bucket] - 1:02d}"
        record["seed"] = SEED + index
    args.work.mkdir(parents=True, exist_ok=True)
    with (args.work / "prompts.jsonl").open("w", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps(record, ensure_ascii=False) + "\n")
    print(f"{len(records)} prompts", flush=True)


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    with path.open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]


def run_generate(args) -> None:
    prompts = _read_jsonl(args.work / "prompts.jsonl")
    if args.limit:
        prompts = prompts[:args.limit]
    output = args.work / "generations.jsonl"
    identity = {
        "model": {"path": str(args.model.resolve()), "sha256": _sha256_file(args.model)},
        "server": {"path": str(args.server), "sha256": _sha256_file(args.server)},
        "prompts_sha256": _sha256_file(args.work / "prompts.jsonl"),
        "max_new_tokens": MAX_NEW_TOKENS, "sampling": {str(k): v for k, v in SAMPLING.items()},
    }
    identity_path = args.work / "generation_identity.json"
    if identity_path.exists() and _load_json(identity_path) != identity:
        raise RuntimeError("generation identity differs from the earlier run")
    _atomic_json(identity_path, identity)
    done = {row["id"] for row in _read_jsonl(output)}
    todo = [p for p in prompts if p["id"] not in done]
    print(f"{len(done)} done, {len(todo)} to generate", flush=True)
    if not todo:
        return

    base = f"http://127.0.0.1:{args.port}"
    log = (args.work / "server.log").open("a")
    process = subprocess.Popen(
        [str(args.server), "-m", str(args.model), "--jinja", "-ngl", str(args.gpu_layers),
         "--n-cpu-moe", str(args.n_cpu_moe), "-t", str(args.threads),
         "-c", str(args.parallel * args.slot_context), "-np", str(args.parallel),
         "--host", "127.0.0.1", "--port", str(args.port), "--no-webui"],
        stdout=log, stderr=subprocess.STDOUT, start_new_session=True)

    def generate(prompt: dict[str, Any]) -> dict[str, Any]:
        request = {"messages": prompt["messages"],
                   "chat_template_kwargs": {"enable_thinking": prompt["thinking"]}}
        if prompt["tools"]:
            request["tools"] = prompt["tools"]
        text = _post(base + "/apply-template", request)["prompt"]
        tokens = _post(base + "/tokenize", {"content": text, "add_special": False,
                                            "parse_special": True})["tokens"]
        body = {"prompt": tokens, "n_predict": MAX_NEW_TOKENS, "seed": prompt["seed"],
                **SAMPLING[prompt["thinking"]], "return_tokens": True,
                "cache_prompt": False}
        response = _post(base + "/completion", body)
        return {"id": prompt["id"], "prompt_text": text, "prompt_tokens": tokens,
                "generated_tokens": response["tokens"], "content": response["content"],
                "stop_type": response.get("stop_type"),
                "tokens_predicted": response.get("tokens_predicted"),
                "timings": response.get("timings", {}),
                "server_settings": response.get("generation_settings")}

    try:
        _wait_ready(base, process, timeout=1800)
        started, produced = time.perf_counter(), 0
        with output.open("a", encoding="utf-8") as handle, \
                concurrent.futures.ThreadPoolExecutor(args.parallel) as pool:
            futures = [pool.submit(generate, prompt) for prompt in todo]
            for count, future in enumerate(concurrent.futures.as_completed(futures), 1):
                row = future.result()
                handle.write(json.dumps(row, ensure_ascii=False) + "\n")
                handle.flush()
                os.fsync(handle.fileno())
                produced += len(row["generated_tokens"])
                rate = produced / (time.perf_counter() - started)
                print(f"{count}/{len(todo)} {row['id']}: {len(row['generated_tokens'])} tokens, "
                      f"stop {row['stop_type']}, {rate:.1f} tok/s overall", flush=True)
    finally:
        os.killpg(process.pid, signal.SIGTERM)
        try:
            process.wait(timeout=60)
        except subprocess.TimeoutExpired:
            os.killpg(process.pid, signal.SIGKILL)
        log.close()


def run_finalize(args) -> None:
    tokenizer = _tokenizer(args.model_dir)
    eog = {tokenizer.convert_tokens_to_ids("<|im_end|>"),
           tokenizer.convert_tokens_to_ids("<|endoftext|>")}
    prompts = _read_jsonl(args.work / "prompts.jsonl")
    generations = {row["id"]: row for row in _read_jsonl(args.work / "generations.jsonl")}
    missing = [p["id"] for p in prompts if p["id"] not in generations]
    if missing:
        raise RuntimeError(f"{len(missing)} prompts have no generation, e.g. {missing[:3]}")
    records, checks = [], {"prompt_retokenization_mismatches": [],
                           "content_decode_mismatches": []}
    for prompt in prompts:
        row = generations[prompt["id"]]
        generated = row["generated_tokens"]
        stopped = row["stop_type"] == "eos"
        if stopped != (bool(generated) and generated[-1] in eog):
            raise RuntimeError(f"{prompt['id']}: stop type and final token disagree")
        if len(generated) != row["tokens_predicted"]:
            raise RuntimeError(f"{prompt['id']}: token count differs from tokens_predicted")
        hf = tokenizer(row["prompt_text"], add_special_tokens=False)["input_ids"]
        if hf != row["prompt_tokens"]:
            checks["prompt_retokenization_mismatches"].append(prompt["id"])
        body = generated[:-1] if stopped else generated
        if tokenizer.decode(body) != row["content"]:
            checks["content_decode_mismatches"].append(prompt["id"])
        tokens = row["prompt_tokens"] + generated
        scored = [0] * len(row["prompt_tokens"]) + [1] * len(generated)
        records.append({**prompt, "prompt_text": row["prompt_text"], "content": row["content"],
                        "stopped": stopped, "_tokens": tokens, "_scored": scored})

    corpus_path = args.work / "corpus.jsonl"
    tokens_path = args.work / "tokens.json"
    with corpus_path.open("w", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps({k: v for k, v in record.items() if not k.startswith("_")},
                                    ensure_ascii=False) + "\n")
    tokens_path.write_text(json.dumps(
        [{"id": r["id"], "tokens": r["_tokens"], "scored": r["_scored"]} for r in records]),
        encoding="utf-8")
    template = args.model_dir / "chat_template.jinja"
    generation_identity = _load_json(args.work / "generation_identity.json")
    canonical = {
        "schema": SCHEMA,
        "seed": SEED,
        "quotas_per_split": {f"{s}/{lang}": q for (s, lang), q in QUOTAS.items()},
        "max_context_tokens": MAX_CONTEXT_TOKENS,
        "scoring": ("the final assistant turn's generated tokens, including the "
                    "end-of-generation token; the prompt (with any prefilled think "
                    "block) is context"),
        "generation": generation_identity,
        "sources": {**SOURCES, "document": {"dataset": "calibration corpus v2",
                                            "path": str(args.documents),
                                            "sha256": _sha256_file(args.documents)}},
        "chat_template": {"path": str(template), "sha256": _sha256_file(template)},
        "tokenizer_sha256": _sha256_file(args.model_dir / "tokenizer.json"),
        "prompts": {"path": str(args.work / "prompts.jsonl"),
                    "sha256": _sha256_file(args.work / "prompts.jsonl")},
        "corpus": {"path": str(corpus_path), "sha256": _sha256_file(corpus_path)},
        "tokens": {"path": str(tokens_path), "sha256": _sha256_file(tokens_path)},
        "conversations": [{
            "id": r["id"], "stratum": r["stratum"], "language": r["language"],
            "split": r["split"], "thinking": r["thinking"], "source_key": r["source"]["key"],
            "stopped": r["stopped"], "token_count": len(r["_tokens"]),
            "scored_target_count": sum(r["_scored"][1:]),
            "content_sha256": sha256_bytes(r["content"].encode("utf-8")),
        } for r in records],
    }
    summary: dict[str, Any] = {"checks": {k: len(v) for k, v in checks.items()}}
    for split in SPLITS:
        rows = [r for r in records if r["split"] == split]
        summary[split] = {
            "conversations": len(rows),
            "tokens": sum(len(r["_tokens"]) for r in rows),
            "scored_targets": sum(sum(r["_scored"][1:]) for r in rows),
            "hit_token_limit": sum(not r["stopped"] for r in rows),
            "strata": {stratum: {
                "conversations": sum(r["stratum"] == stratum for r in rows),
                "scored_targets": sum(sum(r["_scored"][1:]) for r in rows
                                      if r["stratum"] == stratum),
                "hit_token_limit": sum(not r["stopped"] for r in rows
                                       if r["stratum"] == stratum)}
                for stratum in dict.fromkeys(r["stratum"] for r in rows)},
        }
    _atomic_json(args.output, {
        "schema": SCHEMA + ".manifest",
        "status": "complete",
        "canonical_manifest": canonical,
        "canonical_manifest_sha256": sha256_bytes(canonical_json_bytes(canonical)),
        "summary": summary,
        "check_details": checks,
    })
    print(json.dumps(summary, indent=1), flush=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("command", choices=("prompts", "generate", "finalize"))
    parser.add_argument("--model-dir", type=Path, default=ROOT / "data/qwen36_35b_base")
    parser.add_argument("--work", type=Path, default=ROOT / "data/qwen36_chat_corpus_v2")
    parser.add_argument("--sources", type=Path, default=ROOT / "data/qwen36_chat_corpus_v1/sources")
    parser.add_argument("--v1-corpus", type=Path,
                        default=ROOT / "data/qwen36_chat_corpus_v1/corpus.jsonl")
    parser.add_argument("--documents", type=Path,
                        default=ROOT / "data/qwen36_calibration_corpus_v2/corpus.jsonl")
    parser.add_argument("--output", type=Path,
                        default=RCO / "reports/qwen36_chat_corpus_v2_manifest.json")
    parser.add_argument("--model", type=Path,
                        default=ROOT / "data/qwen36_reference_gguf/Qwen3.6-35B-A3B-Q6_K.gguf")
    parser.add_argument("--server", type=Path,
                        default=ROOT / "experiment/build-cuda/bin/llama-server")
    parser.add_argument("--gpu-layers", type=int, default=99)
    parser.add_argument("--n-cpu-moe", type=int, default=30,
                        help="layers whose experts stay on the CPU")
    parser.add_argument("--threads", type=int, default=12)
    parser.add_argument("--parallel", type=int, default=4)
    parser.add_argument("--slot-context", type=int, default=MAX_CONTEXT_TOKENS + MAX_NEW_TOKENS + 256)
    parser.add_argument("--port", type=int, default=18090)
    parser.add_argument("--limit", type=int, help="first N prompts only (smoke tests)")
    args = parser.parse_args()
    {"prompts": run_prompts, "generate": run_generate, "finalize": run_finalize}[args.command](args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
